version: '3.1'
services:
  back-end:
    image: node:latest
    container_name: container_back-end_covid
    restart: always
    env_file:
      - ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - PORT=$PORT
    working_dir: /usr/app
    volumes:
      - ./back-end:/usr/app
    command: bash -c "npm install && npx sequelize db:create && npx sequelize db:migrate && npm run dev"
